version: "3.8"

services:
    php:
        build: .docker/php
        container_name: laravel-php
        volumes:
            - ./:/var/www
            - .docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-debug.ini
            - .docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - XDEBUG_MODE=develop,debug

    nginx:
        image: nginx
        ports:
            - "8000:80"
        container_name: laravel-nginx
        volumes:
            - ./:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: postgres:16
        ports:
            - "5432:5432"
        volumes:
            - .docker/db/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=laravel-todo-app-user
            - POSTGRES_PASSWORD=laravel-todo-app-pwd
            - POSTGRES_DB=laravel-todo-app
